### ISSUE TITLE
Will there be version/support for Laravel 6.x.x?

### ISSUE THREAD

**Issue by jekabsmilbrets** [railken/laravel-eloquent-join#1]
Will there be version/support for Laravel 6?

**Comment by railken** [comment]
Hi, i have started to work to my own version of "joiner" as i saw no progress with the MorphMany to the main repo

Here are some [tests](https://github.com/railken/eloquent-mapper/blob/master/tests/JoinerTest.php)

So i won't make any significant change to this repo in the future.

If the needed change is only https://github.com/fico7489/laravel-eloquent-join/commit/119deb01cee956d93d338741c7b2de7097bd9ff2 i don't have any problem

**Comment by jekabsmilbrets** [comment]
Yeah, I tried Your new repo, It too requires  Laravel <6.x;

So yeah, if could just merge fico7489@119deb0 for laravel 6 support, it would be great :)

**Comment by railken** [comment]
Ouch, you're right, i will fix it later.

I have updated composer.json with the version `6.*`

I didn't have time to make a full test, but all tests in `/tests/` seems to work, open a new issue if you find any problem.

I will release a new version when i will have finished to fix travis with laravel 6.x
